### ISSUE TITLE
Multiple ongoing topics with dependencies on another

### ISSUE THREAD

**Issue by hsujeremyc** [ajvondrak/git-topics#4]
I’ve run across my first bigger confusion using `git topics` - having multiple separate topics that depend on each other.

1. Let’s say I have 2 fairly large tickets. I finish one (branch `A`), push it to code review. Now I want to start my second ticket, but it has lots of dependencies on branch A. So instead of `git topics start B`, I just go old-fashioned and do `git checkout -b B`off of branch `A` and start making several commits on `B`.
2. Now code review starts on `A` and I make some changes to `A`. Should I rebase `A` into `B` or merge `A` into `B`? I don’t think the decision matters that much here since it’s still in code review and neither are in `develop` yet. 
3. Eventually, we run `git topics integrate A` and start QA. If we find bugs, we push them to `A` and run `git topics integrate A` again. At this point, the same question arises - do we rebase or merge `A` into `B`? Again, it doesn't matter much since `B` hasn't been integrated yet.
4. Now the fun part - `A` isn't ready to be finished and released yet, but `B` is ready to be integrated. We run `git topics integrate B` and it's in develop now. We still somehow find a bug on `A` and do the same (push fix to branch `A`, `git topics integrate A`). Now, if we rebase `A` into `B`, `B`'s history gets rewritten and won't match up properly with what's in `develop`. Using `merge` and `git topics integrate B` will just add two merge commits to develop (merge commit of `A` into `B` and another for merging `B` into develop). There will be no actual code changes.

For steps 2 and 3, rebasing "felt" better to me and seemed to preserve history in a cleaner way, but with step 4 pretty much requiring the step to merge, should we just use `merge` in all scenarios? Of course there are other scenarios that say maybe all of the work should have just been in one topic instead of 2, or that `A` should be finished before `B` gets integrated, but I'm not sure how realistic it is to always force those rules.

Curious what you think is the "git topics way" for handling this.

**Comment by ajvondrak** [comment]
Lots of words to say on this, not a lot of time to write them down. :weary: Until now... :smiling_imp:

The short cop-out answer is that topic branches should be as independent as possible. But of course sometimes there's no avoiding it.

[The way the git team does it](https://git-scm.com/docs/gitworkflows), the basic answer for managing dependencies is with merges:

> There are two main tools that can be used to include changes from one branch on another: git-merge[1] and git-cherry-pick[1].
>
> Merges have many advantages, so we try to solve as many problems as possible with merges alone. Cherry-picking is still occasionally useful; see "Merging upwards" below for an example.
>
> Most importantly, merging works at the branch level, while cherry-picking works at the commit level. This means that a merge can carry over the changes from 1, 10, or 1000 commits with equal ease, which in turn means the workflow scales much better to a large number of contributors (and contributions). Merges are also easier to understand because a merge commit is a "promise" that all changes from all its parents are now included.

[...]

> Make a side branch for every topic (feature, bugfix, ...). Fork it off at the oldest integration branch that you will eventually want to merge it into.
>
> Many things can then be done very naturally:
>
> * To get the feature/bugfix into an integration branch, simply merge it. If the topic has evolved further in the meantime, merge again. (Note that you do not necessarily have to merge it to the oldest integration branch first. For example, you can first merge a bugfix to _next_, give it some testing time, and merge to _maint_ when you know it is stable.)
>
> * If you find you need new features from the branch _other_ to continue working on your topic, merge _other_ to topic. (However, do not do this "just habitually", see below.)
>
> * If you find you forked off the wrong branch and want to move it "back in time", use git-rebase[1].

Since merges act as "promises", merging `A` into `B` is a reasonable way of saying "hey, `B` needs whatever changes `A` had at this exact point where I merged". Like so:

```console
$ git log --oneline
717cccf (HEAD -> master, develop) root
```
```console
$ git topics start A
Switched to a new branch 'A'
$ git commit --allow-empty -m 'A1'
[A 7cefdbc] A1
$ git log --oneline
7cefdbc (HEAD -> A) A1
717cccf (master, develop) root
```
```console
$ git topics start B
Switched to a new branch 'B'
$ git merge --no-ff A
Already up to date!
Merge made by the 'recursive' strategy.
$ git commit --allow-empty -m 'B1'
[B bbcf4bf] B1
$ git log --oneline
bbcf4bf (HEAD -> B) B1
e4ee42a Merge branch 'A' into B
7cefdbc (A) A1
717cccf (master, develop) root
```

You can then make further changes to `A` that `B` may or may not need:

```console
$ git checkout A
Switched to branch 'A'
$ git commit --allow-empty -m 'A2'
[A 19decd3] A2
$ git log --oneline
19decd3 (HEAD -> A) A2
7cefdbc A1
717cccf (master, develop) root
```
```console
$ git checkout B
Switched to branch 'B'
$ git commit --allow-empty -m 'B2'
[B fe38686] B2
$ git log --oneline
fe38686 (HEAD -> B) B2
bbcf4bf B1
e4ee42a Merge branch 'A' into B
7cefdbc A1
717cccf (master, develop) root
```

Should we find that `B` still needs the `A2` change, we can merge again:

```console
$ git merge --no-ff A
Already up to date!
Merge made by the 'recursive' strategy.
$ git commit --allow-empty -m 'B3'
[B f44d8eb] B3
$ git log --oneline
f44d8eb (HEAD -> B) B3
fe36a56 Merge branch 'A' into B
fe38686 B2
19decd3 (A) A2
bbcf4bf B1
e4ee42a Merge branch 'A' into B
7cefdbc A1
717cccf (master, develop) root
```

Doing this *too* much makes me a little queasy, though. I would get worried about what happens when I make changes on `A`, then decide `B` is finished **without** the additional `A` changes:

```console
$ git commit --allow-empty -m 'A3'
[A d282576] A3
$ git log --oneline
d282576 (HEAD -> A) A3
19decd3 A2
7cefdbc A1
717cccf (master, develop) root
```
```console
$ git log --oneline A --not B
d282576 (A) A3
```
```console
$ git topics integrate B
Already up to date!
Merge made by the 'recursive' strategy.
$ git topics finish B
Already up to date!
Merge made by the 'recursive' strategy.
$ git log --oneline master
000e6a0 (HEAD -> master) Merge branch 'B'
f44d8eb (B) B3
fe36a56 Merge branch 'A' into B
fe38686 B2
19decd3 A2
bbcf4bf B1
e4ee42a Merge branch 'A' into B
7cefdbc A1
717cccf root
```

In effect, we'll have *partially* released topic `A`. Maybe that's what you want - that's what the merge commits say on the tin, after all. "`B` needs these changes from `A` at this specific point in time". But it also seems possible to do this by mistake, leaving out some vital fix from `A3`. Maybe that's just the nature of dependencies, though. :man_shrugging:

`<historical-aside>`
Early on, I had considered making a `git topics use <other-topic>` command to "declare dependencies" between topics, which amounted to just doing a `git merge --no-ff` as illustrated above. In the end [I decided against it](https://github.com/ajvondrak/git-topics/commit/19e70680590b8324c610d67c244cb6f61798d38c), since I didn't want to bother making `git topics list` do O(n^2) checks in the number of topics to give you pairwise `B uses A` / `A used by B` messaging. Such logic *is* actually present in the git.git [cook](https://github.com/git/git/blob/todo/cook) script, which I've cribbed a lot off of already. So maybe `git topics use` will make a comeback someday.
`</historical-aside>`

For all the semantic information they carry, you rightly point out that the rat's nest of merges can still be messy. No argument here. It may therefore be reasonable to rebase at certain points, particularly early on in development before anything hits QA. It's largely a judgement call. Linus Torvalds has some great rules of thumb for [when to rebase vs when to merge](https://www.mail-archive.com/dri-devel@lists.sourceforge.net/msg39091.html).

In searching for examples of dependent topic branches on the git.git repo, I remember it also seeming common to just rewrite history (they often call it "rerolling" a patch). So if `B` was getting too messy with merges from `A`, maybe you just "flatten out" your history.

So say we hadn't finished `B` yet:

```console
$ git checkout master
Switched to branch 'master'
$ git log --format='%H' | tail -1 | xargs git reset --hard
HEAD is now at 717cccf root
```

But to your point about the dangers of rebasing in step 4, let's say `B` **is** still integrated:

```console
$ git topics
Topics merged to develop:
  (use 'git topics finish' to promote to master)

    B

Topics not yet merged:
  (use 'git topics integrate' to promote to develop)

    A

$ git log develop --oneline
c5ac44e (develop) Merge branch 'B' into develop
f44d8eb (HEAD -> B) B3
fe36a56 Merge branch 'A' into B
fe38686 B2
19decd3 A2
bbcf4bf B1
e4ee42a Merge branch 'A' into B
7cefdbc A1
717cccf (master) root
```

`B` needs the `A3` changes - the third merge from `A` in its history. Getting way too messy, so we decide to rewrite the history to make it cleaner.

There's a subtlety here. If we're assuming `A` & `B` _should_ still be separate topics, it doesn't make the most sense to `git rebase A`. That would merely make `B` look like a single long continuation of `A`, so why should it even be a separate branch at that point? I.e.,

```
# If we did git rebase A, why did we not just commit B1-B3 on A directly?

                 A              B
                 |              |
root - A1 - A2 - A3 - B1 - B2 - B3

# Rather, it'd make more sense to have at least one merge commit:

                 A
                 |
root - A1 - A2 - A3                             B
     \            \                             |
      *----------- dependency merge - B1 - B2 - B3
```

So we have to be careful with the rebase operation:

```console
$ git rebase -i --keep-empty master
```

Rebase script before:

```
pick 7cefdbc A1
pick bbcf4bf B1
pick fe38686 B2
pick 19decd3 A2
pick f44d8eb B3
```

Rebase script after:

```
exec git merge --no-ff A
pick bbcf4bf B1
pick fe38686 B2
pick f44d8eb B3
```

```console
Executing: git merge --no-ff A
Already up to date!
Merge made by the 'recursive' strategy.
Successfully rebased and updated refs/heads/B.
$ git log --oneline
3c9b9f1 (HEAD -> B) B3
d5a2494 B2
4bf0851 B1
ea678c1 Merge branch 'A' into HEAD
d282576 (A) A3
19decd3 A2
7cefdbc A1
717cccf (master) root
```

But now that we've rewritten the history, the commits we previously integrated have been duplicated. :scream:

```console
$ git log --oneline --left-right B...develop
< 3c9b9f1 (HEAD -> B) B3
< d5a2494 B2
< 4bf0851 B1
< ea678c1 Merge branch 'A' into HEAD
> c5ac44e (develop) Merge branch 'B' into develop
< d282576 (A) A3
> f44d8eb B3
> fe36a56 Merge branch 'A' into B
> fe38686 B2
> bbcf4bf B1
> e4ee42a Merge branch 'A' into B
```

However, one thing with git-topics vs git-flow is that `develop` **isn't all that special**. Since we don't merge `develop` into `master`, `develop` just exists as its own long-lived independent branch. If we need to rewrite it, we can. That's what `git topics reintegrate` is for:

```console
$ git topics
Topics not yet merged:
  (use 'git topics integrate' to promote to develop)

    A
    B

$ git topics reintegrate
```

Here, I'll simply select to `pick B`:

```console
Rewinding develop...
Reintegrating B (1/1)
Already up to date!
Reintegrated develop
```

But, since `B` also contained _all_ of `A`, both have technically been integrated:

```console
$ git topics
Topics merged to develop:
  (use 'git topics finish' to promote to master)

    A
    B

$ git log --oneline develop
4d162bf (HEAD -> develop) Merge branch 'B' into develop
3c9b9f1 (B) B3
d5a2494 B2
4bf0851 B1
ea678c1 Merge branch 'A' into HEAD
d282576 (A) A3
19decd3 A2
7cefdbc A1
717cccf (master) root
```

The downside is, of course, having to let people know that you've clobbered the `develop` branch and all that. I *feel* like this would be less of a pain in the ass if it were more common, though - people would expect the `develop` branch to be less stable.

One possible alternative is using an even less stable branch than `develop`, which git.git calls `pu` for "proposed update". There's some limited support for that in git-topics, where you could instead say `git reintegrate --onto pu`. But I personally haven't had a good justification for this in practice, when the `develop` branch is where we _need_ to merge to do integration testing.

You could also keep the `develop` branch messy with duplicate commits and at least rest easy knowing that `master` will be clean once we merge there. Or maybe strike a balance by keeping it messy **for now** and reintegrating at some well-defined point in the future (e.g., at the next release or on a specific schedule). I feel like this should probably be a common practice anyway, with all the merge commits that wind up cluttering `develop` during the test/integrate/test/integrate cycle.

Anyway, I hope that's sort of answered your question. 😅 I would err on the side of "use merge", but it does become a judgement call. You can make lots of things work, and there are plenty of reasons to rebase. And moreover, I think there are always going to be weird corner cases, **especially** with dependent topic branches, which ideally should be infrequent anyway.

**Comment by hsujeremyc** [comment]
Wow, thanks for all the words. It definitely makes me think about the process more and get more insight to how complicated release strategies can be.

In an effort to try and keep this short, I think I tend to agree to err on the side of merge. Rebasing is probably fine when everything is still private to yourself (as described in the Linus link), but once things get pushed up to even code review, it's probably best to just start using merges.

> Or maybe strike a balance by keeping it messy for now and reintegrating at some well-defined point in the future

I do like this idea to help keep develop cleaner. Might try and start doing it here and there for facelift.

Again, thanks for the words. I didn't get a "clean" solution out of it, but I did get a peace of mind in moving forward with a case by case viewpoint that errs on the side of merges and I'm totally cool with that.
